### PR TITLE
Paste url

### PR DESCRIPTION
**Pull request by slarti-b**
One more usability improvement that I wanted, so I did it and hoped you do too :)  My workflow is to open the issue in Jira then put it into the stopwatch.  So, I often end up copying the issue ID from the URL and pasting it into the stopwatch.  I thought it would be easier if I could just copy/paste the whole URL and the stopwatch would parse out the issue key for me.

Yes, I know I could just type the issue ID, but that would be too simple :)

### CODE REVIEW

**Comment by slarti-b** [comment]
Hi,

What do you think of this?  notice you have committed version bumps, so are you planning a new version soon?  Any chance of getting this in - I've been using it for a while now and it's a small thing that actually makes a big difference to usability (for me at least)

**Comment by carstengehling** [comment]
Hey Adam. A lot of stuff has happened since your pull-request, so instead of trying to merge it, I'll copy your code into my current master - you'll of course get credit for it.

**Comment by slarti-b** [comment]
No problem. Thanks!  Might be easiest to look at my original branch to see the changes - when I did the first fix on master instead of a branch then tried to move it to a branch, I messed my repo up a bit and it doesn't like rebasing now, seems to show more changes than need, but just whitespace and stuff.  My original commits only changed like 1 or two files...

**Comment by carstengehling** [comment]
Adam try to pull the latest commits, that I've just pushed. I try to seperate the functionality and responses into manageable chunks - also to make the code testable. Could you build it and do a QA on the feature now? I hope I've thought of all scenarios in the tests.

**Comment by carstengehling** [comment]
I tried to make the combobox capture an actual Paste event, but it turned out to be too much hassle with an editable combobox (that actually contains a textbox inside it). So I hooked into the TextUpdate instead.

**Comment by slarti-b** [comment]
Hi,

Yeah, I'd also started out trying to make it a paste event, and ended up doing textChanged because of the combo box complexities :)  Will try your latest version and let you know

**Comment by slarti-b** [comment]
Have tried your version tonight.  Seems to mainly work.  It parses sightly differently to mine - if I paste in a URL for an issue in a different Jira, yours would assume you mean that issue key at the Jira I am connected to.  For example, if I paste https://jira.example.com/browse/FOO-1 into the issue key field it parses to FOO-1, even though I am connected to a different Jira.  But I can see an argument for that.

The only thing I am not convinced by is the  
```
if (!text.Contains(@"browse/"))
	return "";
```
This means if I enter FOO-1BAR then it empties the field (actually, I never get that far if typing - at FOO-1B it clears).  I maybe wouldn't do that - but might by mistake.  I do sometimes use a note in the field, in order to use the timer, when getting a phone call from a colleague which I need to log time on but doesn't yet have an issue.  If I type _"new issue related to FOO-1"_ it clears too.  But primarily, the issue is if typing the issue key and I make a small mistake (add an extra letter) it clears and I have to restart.  Suggest changing the `return "";` there to `return text;` (or even save the original text before trimming to return here).  

Also on principle - if we can't parse the key we should leave it alone.

**Comment by carstengehling** [comment]
I totally agree - nice spotted. I admit, that my focus changed a bit while adding to the function and the tests.

I actually could make the parsing much simpler with just a regular expression, so that something like this:

43#"&#%"MYKEY-345%¤&#%%&

will be parsed as MYKEY-345. I was initially just concerned about the side effects. But as I've done now - the parsing is needlessly complex.

**Comment by slarti-b** [comment]
Could do. My code started by checking that what you had entered started with the URL for your Jira site (as configured in settings).  My (admittedly somewhat contrived) example of putting “new issue related to FOO-1" would still change to FOO-1 otherwise.  I’d initially gone fairly restrictive: only match things I know are URLS for this Jira instance. But it’s certainly a reasonable approach to simply match anything that looks like an issue ID.

Would need to handle the situation that there were several (for example: I do a search in Jira for parent = FOO-1 then click an issue FOO-99, I end up with https://jira.carus.com/browse/FOO-99?jql=parent%20%3D%20FOO-1 as the URL, so it contains two issue-IDs).  Your current implantation doesn’t have a problem here, since it ignores query strings (not sure now if mine did…)

**Comment by carstengehling** [comment]
Concerning the multiple issue keys: I would say, that it should simply use the first detected.

So what about this simple solution:

If a issue key with the pattern [a-z0-9_]+-\d+ is detected, then always extract and return this. Otherwise: always just return the text unaltered.

All this is really only a concern because we don't want to intrude on users typing in the combobox. So in addition maybe I should give it a go again with trying to hook into the paste WM_ message.

**Comment by slarti-b** [comment]
Yeah, paste-only would be nice.

If it’s not paste-only (even if it is, but then only on paste) it would not accept “follow-up to FOO-1” or some such (rewrite to “FOO-1”) but those cases are unlikely.  Main thing is a typo doesn’t empty the field. If we want an extra check then we could check it starts with the Jira URL they have configured and only if it does use the regexp approach you describe?

**Comment by carstengehling** [comment]
Fooled the computer again.

I've managed to hook into the real WM_PASTE message from the Win32 API. So now searching/matching for keys only actually happens on pase (both CTRL-V and by context-menu). Therefore I've also simplified the matching algorithm to simply grab the first pattern match (greedy) and return it. And if no match - return the original text.

Grab the latest commit, take it for a spin, and let me hear what you think.

**Comment by slarti-b** [comment]
Looks good!  And works as far as I can tell.  Closing this PR.

**Pull request closed without merging**
