### PR TITLE
Issue #100 Use Jira configuration for hours per day

### LINKED ISSUE #100: Auto-Adjusted Estimate is wrong if several days
When you log time, you have the options on what to do with the remaining estimate.  Options are auto adjust, leave along, reduce by and set to, same as in Jira.

The Adjust automatically option shows what it should be adjusted to in brackets.  However, this seems to be wrong for issues with several days remaining.  E.g. logging 1 minute:
image
It's saying "1d 5h..." for 29.* hours  So, it seems to be treating 1 day as 24 hours.  It should instead use the value of a day from Jira, to be consistent with entered times and Jira generally.

I'll try and find time to look at this, especially since I added the remaining estimate stuff so it's probably my fault, but wanted to log an issue :)

### PR DESCRIPTION
**Pull request by slarti-b**
Now uses configuration from jira for number of (work) hours per day when presenting a time in a jira days/hours/minutes format

Fixes #100

### CODE REVIEW

**Comment by carstengehling** [comment]
@slarti-b Adam I prepared a new version with your changes the other day (sorry it takes so long - the days run fast at the moment...) And something strange happened, when I upgraded in the middle of the day: 

1) I had Jira running with an issue timer, that was at ~1h 20m
2) I shut down Jira (with the option "save timers, keep timer running"
3) I upgraded to new version (with this feature in it)
4) I started Jira, and now the time displayed was something huge (999h or something like it).

Unfortunately I didn't think to take a screenshot. I just want to ask you (before releasing): Have you experienced anything similar?

**Comment by slarti-b** [comment]
@carstengehling : I haven't, but I don't usually run with "keep timers running".  Might be related to the start time not being there in the old version (although it should work)

**Comment by carstengehling** [comment]
It's probably just because I didn't upgrade from a "clean slate" (ie. made sure all timers were reset) before upgrading :) I'll make a note of it on the release page, then that must be good enough. I'll release it today.

Thanks for all your hard work BTW - it's very appreciated!

**Comment by slarti-b** [comment]
Thanks!  And thanks for the app - very useful.

**Pull request merged**
