### PR TITLE
added pause active timer at logout & minimize to tray

### PR DESCRIPTION
**Pull request by fjung**

### CODE REVIEW

**Comment by carstengehling** [comment]
Hey Frederik, thank you for your pull request. Just so I understand the first feature correctly: Is it an option to pause time-tracking when you LOCK your computer? Because normal "logout" of windows would normally quit all applications, including Jira Stopwatch.

**Comment by fjung** [comment]
Yes, your rigth.
i mean system lock.
key’s: [windwos] + [L] ;)

Von: Carsten Gehling [mailto:notifications@github.com]
Gesendet: Donnerstag, 14. Januar 2016 09:12
An: carstengehling/jirastopwatch
Cc: Frederik Jung
Betreff: Re: [jirastopwatch] added pause active timer at logout & minimize to tray (#4)


Hey Frederik, thank you for your pull request. Just so I understand the first feature correctly: Is it an option to pause time-tracking when you LOCK your computer? Because normal "logout" of windows would normally quit all applications, including Jira Stopwatch.

**Comment by carstengehling** [comment]
Cool - I've added it and will run through it asap. If it works out fine, I'll release a new version. Thanks for the code :-) :+1:

**Comment by carstengehling** [comment]
Frederik I looked through the code and tested your features. And it's very neat. :-)

One question regarding "pause timer on lock PC. When the user unlocks the PC, the timer does not resume. Was this intended? I am thinking that I'll change this, so the user can choose that the timer automatically resumes. But I'll keep the other use-case also, if you intentionally wanted it so.

**Comment by fjung** [comment]
yes, it was intended.
it should be optional.

**Pull request merged**
