### PR TITLE
Flexible issue count

### LINKED ISSUE #38: Feature Request: Add/remove rows dynamically
I am in a position where I often get asked for help from other members of my team and/or input from other parts of the organisation. I would obviously like to log time on these issues, but it means the number of issues I want to have in the stopwatch app is a bit variable.  I don't like having a bunch of empty rows just in case but would prefer to be able to just click a button and add a row (or remove one) without going in to the settings screen.  

What do you think?  I'd be quite happy to implement this and send a PR (in fact, I had a play around to see how easy it would be already).

Add row is fairly straightforward. Delete/remove has a couple of options in temrs of implementation:
- It just deletes the row.  if you have un-logged time on it then hard luck (this is consistent with the behaviour of the clear/reset button today)
- The delete button is disabled if you have un-logged time (you have to either log the time or clear/reset before deleting)
- It prompts/warns you if you have un-logged time

I'm inclined towards the first simply for consistency.

Obviously, the delete row button would be disabled when only one row remains

### PR DESCRIPTION
**Pull request by slarti-b**
This fixes #38.  

It's not quite what my comment showed - I used a different icon and re-ordered slightly after consulting my resident UI expert, but it's the same principle.

I had initially started with this as an additional option to the existing issue count you could set in the settings.  However, based on your comment that "this should replace the option in the settings dialog" (which I agreed with when I thought about it a bit) I have removed the old settings and it now just uses the add/remove buttons.  This was done in the final commit.

### CODE REVIEW

**Comment by carstengehling** [comment]
Thank you for the PR. However, you've built it on top of PR #37, which makes it difficult for me to test and merge it seperately. Can you change it, so that it is based on Master branch instead?

**Comment by slarti-b** [comment]
I think I've re-done the branch as you wanted.  To be honest, I've only ever really used git for my personal projects (we are still using svn at work for the moment) but I think it is now branched from the correct place.

**Comment by carstengehling** [comment]
Sorry for the late reply - I've had some tough days... I am going to do some changes to the UI - I don't fully agree with your UI expert. For example I'd like the + sign to be placed at the top. Right now, if you want to add multiple rows at a time, the + sign will move down on every click - which means you need to move the mouse pointer as well. And I'll probably also make the "remove" icon a little less prominent.

**Comment by slarti-b** [comment]
Fair enough.  Re the add button: I suppose it depends on the use case: if you are adding one then having it at the bottom makes more sense to me (since you are adding one at the bottom).  If you are adding several, then as you say it keeps moving which is annoying.  Would it be worth considering having it in both places?

**Comment by carstengehling** [comment]
I'm trying out a tweak to the whole layout to make it less cluttered:

image

What do you think?

**Comment by slarti-b** [comment]
Looks good!

Adam



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by carstengehling** [comment]
Hey Adam, finally done here. There was a strange bug regarding the scrollbar and the IssueControls not being positioned correctly when adding many of them (there was a huge blank area in the top of pMain. I fixed that too - and also added a little color to the icons.

Try to build this and let me know what you think.

**Comment by slarti-b** [comment]
Hi,

Have updated to your master and noticed one issue.  in the settings form the "Allow control over remaining estimate" is now wrongly positioned:
2016-11-01 10_23_16-foton
(The blue line is actually the top of the OK button).

I can send a PR, but it's probably as easier to just move it than merge :)

Also, when I first open it I get the status as expected in the bottom bar:
stopwatch status
But if I then click the plus to add a new row this changes to a number, which changes as I change the number of issues:
stopwatch number
Is this some debugging left in?

I'll use this version and let you know if I find anything else.

**Comment by carstengehling** [comment]
Haha - yeah the latter was some debugging - I'll fix it :-) I noticed the former as well just now when dealing with tab order in the Settings form. So it's already fixed.

**Comment by carstengehling** [comment]
Try to pull the latest commits and build again. Both things should be fixed now.

**Pull request merged**
